### PR TITLE
Support touch events in jquery UI (useful for sortable steps)

### PR DESCRIPTION
**Pull request by webplate**
### What does/resolve this PR? 
I've finally found a simple solution for sortable steps on tablets and smart-phones (touch events). As a side effect it enables touch interactivity on jquery UI (which is good for the future IMHO).

It's a really small script not making noticeable overhead.

### CODE REVIEW

**Comment by webplate** [comment]
@nicolasleger I'm wondering, should I put the minimized version or the readable version. I'd hope rails would minimize the js and cache it in production but is it the case in our setup ?

**Comment by nicolasleger** [comment]
@webplate better to put the official minified in `public` folder to avoid unnecessary minifying on non custom code.

**Comment by webplate** [comment]
You're right this would be useless minifying. But I don't get if I should put it in public (make an assets / javascript  dir in it?) OR in vendor (where there is already custom code: leaflet routing) ?

Both would work, but I'm wondering of the right semantical place.

What should be in public ? what should be in vendor ?

**Comment by webplate** [comment]
I guess I'll put it in public/javascript/
If that's OK with you :)

**Comment by nicolasleger** [comment]
Sorry I have not a clear answer to provide except outside precompiling assets / app folder.
Generally in other applications `public/javascript/` (easy for routing process since it is the static folder).
But more `vendor/assets` according to documentation see links below.

- http://guides.rubyonrails.org/asset_pipeline.html#how-to-use-the-asset-pipeline
- http://guides.rubyonrails.org/asset_pipeline.html#asset-organization

**Comment by webplate** [comment]
Then for consistency and as the docs indicate:
vendor/assets is for assets that are owned by outside entities, such as code for JavaScript plugins and CSS frameworks.
I'll put it in vendor/assets/javascripts
It's with leaflet-routing.js which makes sense.
It is a known path for js for rails and thus permits short ref for loading.

**Comment by webplate** [comment]
If anyone with a smartphone / tablet could test this ? You should be able to add steps and to reorder them on touch devices.
Test it at: https://covoli-dev-pr213.scalingo.io/trajets/nouveau

**Comment by maxb29** [comment]
Working well for me (on Android 6.0.1) !

**Comment by webplate** [comment]
Thanks a wonderful lot maxb29 !!

**Comment by webplate** [comment]
I think this is ready, I'm waiting for your review @nicolasleger and if everything is well I'll merge !

**Pull request merged**
