### PR TITLE
Update to minor Rails 5.0.5

### PR DESCRIPTION
**Pull request by nicolasleger**
Linked to https://github.com/covoiturage-libre/covoiturage-libre/pull/186 (to be done after)

### CODE REVIEW

**Comment by webplate** [comment]
Could you resolve the merging conflict @nicolasleger ?
Thanks for the groundwork !

**Comment by nicolasleger** [comment]
Ok I will try at lunch

**Comment by nicolasleger** [comment]
@webplate I just updated the PR fixing the conflict and moving to newly Rails minor `5.0.5`

**Comment by webplate** [comment]
Perfect ! You rock !

**Pull request merged**
