### PR TITLE
hide slaask hotline on small screen

### LINKED ISSUE #178: Problem with the help button on Android
### Current Behavior 
When we open the website in a browser on a smartphone (here Android), we can click on the "help button" in the bottom right corner. On some devices, here Android 4.1.2, you do not have any button to close the dialog:
manque bouton android 4
You still have one on Android 5.1:
android 5 bouton present

That's a critical user experience problem. Also, if we close the tab of the website, and reopen another one, the dialog is still present.

### Expected Behaviour
To have a button in every case to close the dialog.
If we left the website with this dialog opened, he must be closed when we reopen it.

### Steps to Reproduce the Problem
- Open the covoiturage-libre.fr site on its smartphone
- Click on the help button
- Is there a cross to close the chat window? A way to return to the site? (This may depend on your android version)
- Close the tab, reopen another one with covoiturage-libre.fr
- Does the tchat window appear directly (without having clicked the question mark)?

[] Development
[] Production

### Ideas for solving the problem
Not sure if it's a problem from the website or the browser directly?
This bug was reported via the test-group on Facebook. The same problem happens on a windows phone.

### PR DESCRIPTION
**Pull request by webplate**
### What does/resolve this PR? 
Resolve #178.
Slaask was destroying our UI on some small screens by appearing in front without closing option.
We do not control the slaask freemium widget.
As we have already many users on the hotline and as its a lot of work, I chose to reduce slaask visibility. Namely, by hiding it on small screens.

No cloud testing as its a simple hack.

### CODE REVIEW

**Comment by nicolasleger** [comment]
@webplate to validate with the functional team in dev env

**Comment by Poussinou** [comment]
This change is a priority, the volunteers of the hotline are overloaded, and the destruction of the UI is a critical bug knowing that a large percentage of people go through their smartphone to visit the site ...

**Comment by webplate** [comment]
Totally agreeing @Poussinou :D What do you think @AlexBillbao @maxb29 @ndelavergne ? OK to merge ? (I'm waiting for approval as its a functionnal feature we hide here).

**Comment by Poussinou** [comment]
The different changes you will push in the next weeks will help the users to use the website, and otherwise we don't have enough volunteers to handle so many mails, so I'm ok to push this one! We can reverse this change later :)

**Comment by nicolasleger** [comment]
@webplate can we merge it in master?

**Pull request merged**
