### PR TITLE
Fixed validation of emails with trailling spaces

### LINKED ISSUE #207: Email invalide
### Current Behavior 
Lors de l'ajout d'un trajet, à la validation la page indique une erreur lorsqu'il y a un espace vide au début ou à la fin du mail renseigné. Sur téléphone la prédiction rentre automatique le mail avec un espace à la fin, c'est donc assez courant pour moi d'avoir cette erreur. 

### Expected Behaviour 
Pas d'erreur. 

### Steps to Reproduce the Problem  
Faire un nouveau trajet avec un espace vide dans le champs email au début ou à la fin. 

[] Development
[X] Production

### Ideas for solving the problem / Implementing the new functionality  
La regex devrait échapper les caractères vides en début et en fin de champs.

### PR DESCRIPTION
**Pull request by webplate**
### What does/resolve this PR? 
Strip whitespaces before email validation.
Resolve #207 

Edit: Now the stripping is for email, name, description, and phone fields too.

### CODE REVIEW

**Comment by nicolasleger** [comment]
Shouldn't we strip email before saving it to database too?

**Comment by webplate** [comment]
Clearly we should... I can't find it, any clues ?

**Comment by nicolasleger** [comment]
I vote for !
You can use `before_valdiation` callback to do so, see https://stackoverflow.com/a/3268152

**Comment by webplate** [comment]
YES exactly what I was I looking for :)

**Comment by Poussinou** [comment]
@webplate 

> Edit: Now the stripping is for email, name, description, and phone fields too.

Does it mean that the removal of whitespaces is also applied to phone numbers, etc...

**Comment by webplate** [comment]
yep

**Comment by Poussinou** [comment]
One of our testers reported that white space aren't removed in the name and phone number. In the changes you did in this PR, I can see the code who check the email, but I can't see the exact place where phone numbers and everything else is handled.

And I have a question : Why removing the whitespaces from the description?

**Comment by nicolasleger** [comment]
* maybe we should remove all spaces and not only trailing ones for `phone` by using `gsub` instead of `strip`

**Comment by webplate** [comment]
@nicolasleger I don't think so, it would reduce readability a lot. Blanks are useful between numbers.

@Poussinou just look there https://github.com/covoiturage-libre/covoiturage-libre/pull/217/files
I strip on 4 attributes.
The stripping is common good practise as these spaces don't convey any meaning but could disrupt layout (even for description).
What address did the tester use ? This should be functional on https://covoli-dev.scalingo.io/

**Comment by webplate** [comment]
I cannot reproduce on https://covoli-dev.scalingo.io/

**Comment by Poussinou** [comment]
My bad, the user was testing https://covoli-dev.scalingo.io/ but I misspoken in the "manual" (a big text on Facebook) "how to do the tests" for the testers, and I thought that this change removed the white space inside the phone number, sorry! All is ok for this PR!

**Comment by webplate** [comment]
Great !

**Pull request merged**
