### PR TITLE
Factorize mailer subject formatting

### PR DESCRIPTION
**Pull request by nicolasleger**
Add and use an ENV var `MAILER_SUBJECT_PREFIX` for mailers.
To reuse the app on other projects

To test : edit it and send a test mail via `UserMailer.message_sent_notification(Message.new(trip: Trip.new(email "you@example.com")).deliver`

### CODE REVIEW

**Comment by Poussinou** [comment]
@nicolasleger thanks for this second PR!

As for the previous PR, can you maybe developp a little bit more what your PR does?

Please @pimpin @didierclin @flexbox @Alex131089 like for others PR, can you test this one on your own, and report any problem here before I push?

If you want me to remove you from the list of persons I can ask to test the PRs, just ask;)

Ask us if you have any question.

**Comment by nicolasleger** [comment]
I updated the PR description to explain changes and how to test them.

**Comment by AlexBillbao** [comment]
Hello ! It's in my point of vue too early to developp PR in order to dupplicate the platform anywhere. We have so much critical issues to close so that we can have a full operating platform. 

Please @nicolasleger  Could  you help on those issues first ?

The license allows to dupplicate the platform, but it would be a loss of time to dupplicate a non operating platform !

Thanks for you help on the "covoiturage-libre projet",

Alex

**Comment by pimpin** [comment]
This PR is not only usefull for seeding new app instance, but it makes the code cleaner removing duplication. I think this PR should be merged ( if ok ; I do not have ran it and it is not covered but it seems ok to me).

@AlexBillbao What are the top most critical issues you mean ?
Are they those -currently 4- [left to be closed for current milestone](https://github.com/covoiturage-libre/covoiturage-libre/milestones/V2%20MVP) ?
We might need a contributing guide.

**Comment by Poussinou** [comment]
Since @pimpin thinks this PR should be merged, I will push it if nobody is against that.

If I have the time, I will create a contribution guide, with the most important issues clearly mentioned. For now, you can consider that the Issues with label "Epic" are the most important to fix.

**Comment by nicolasleger** [comment]
@Poussinou ok no problem, thanks!

**Comment by thb** [comment]
Bonjour, ça a été mis en staging, et ça fonctionne 👍 
image

(j'ai mis en préfixe sur la staging `MAILER_SUBJECT_PREFIX='[Covoiturage-libre.fr Staging]'`

**Pull request merged**
