### PR TITLE
Organise stylesheets & add colors

### PR DESCRIPTION
**Pull request by flexbox**
First draft still in __WIP__

### CODE REVIEW

**Comment by Poussinou** [comment]
Hi @flexbox thanks for the PR. First of all, sorry for the time to respond, we are all volunteers in the team. :)

For the project, can you write a bigger description of what your PR does? We will test it and then push this PR if all is OK on our test-website;)

Please @pimpin @didierclin @nicolasleger @Alex131089 can you test this PR on your own, and report any problem here before I push? If you want me to remove you from the list of persons I can ask to test the PRs, just ask;)

You can join the test group on facebook here : https://www.facebook.com/groups/covoiturage.libre.test/?fref=ts

Again, thanks for the PR, we want you to developp the website :1st_place_medal:

**Comment by Alex131089** [comment]
@Poussinou I'd prefer to be kept out of the list of testers for now please.

**Comment by Poussinou** [comment]
@Alex131089 OK;)

**Comment by thb** [comment]
it is an old PR, to be deleted

**Pull request closed without merging**
