### PR TITLE
Add MAILER_FROM env config

### PR DESCRIPTION
**Pull request by nicolasleger**
Add and use an ENV var `MAILER_FROM ` for mailers.
To reuse the app on other projects

To test : edit it and send a test mail via `ApplicationMailer.mail(to: "you@example.com", subject: "test", body: "test").deliver`

Check mail previews on http://localhost:3000/rails/mailers

### CODE REVIEW

**Comment by Poussinou** [comment]
@nicolasleger thanks for this third PR

As for the previous PR, can you developp a little bit more what your PR does?

Please @pimpin @didierclin @flexbox @Alex131089 like for others PR, can you test this one on your own, and report any problem here before I push?

If you want me to remove you from the list of persons I can ask to test the PRs, just ask

Ask us if you have any question.

**Comment by nicolasleger** [comment]
I updated the PR description to explain changes and how to test them.

**Comment by AlexBillbao** [comment]
Hello i'm Alex, i answer to users on CVL's Hotline. Some users asked us to code a "reply to" function because when a user contacts a driver, the driver receive an email from this "noreply@covoiturage-libre.fr" adress  ... and so he can not answer directly with the "reply to function" of his mail box.   @nicolasleger  Could you code something to allow this change in the forms that comes on a road trip page ?

**Comment by nicolasleger** [comment]
@AlexBillbao Hello Alex, thanks, I updated the PR with the requested Reply-to behaviour, also fixing factories and Mailer test preview.

**Pull request merged**
